export const BSP_data = [{
  prop: {
    key: "0",
    PRODUCENT: "ATMOS UAV ",
    NAZWA: "Marlyn (MSC) ",
    ROk_WpROWADZENIA_NA_RYNEk: "2020",
    pLATFORMA: "0",
    wymiary_platformy: "160 x 82 x 70 ",
    wymiary_po_złożeniu: "plecak 80 x 75 x 43 ",
    waga_całkowita: "5.7 ",
    maksymalny_udźwig: "1",
    maksymalna_prędkość: "95",
    maks_dopuszczalna_prędkość_wiatru: "start i lądowanie: 45, lot: 55 ",
    liczba_i_rodzaj_silników: "4 elektryczne ",
    maks_czas_lotu_z_maks_obciążeniem: "55",
    metoda_startu: "VTOL ",
    pOZYCjONOWANIE: "0",
    typ_odbiornika_GNSS: "GPS (L1, L2, L5), GLONASS (L1, L2, L3) ",
    obsługa_korekt: "tak ",
    IMU: "tak ",
    SENSORY: "0",
    cyfrowa_kamera: "MicaSense RedEdge-MX/Altum ",
    matryca: "1,2/3,2 ",
    wychylenie_do_zdjęć_ukośnych: "nie ",
    dodatkowe_informacje: "możliwość zamontowania FLIR Duo Pro R ",
    img: "https://sklep.navigate.pl/images/produkty//Drony/Drony_Atmos/Marlyn/nowe2/vsig_images/0_atmos-marlyn_674_453_95.jpg",
    przykładowa_rozdzielczość_obrazów:
      "MX: 8 dla 120 m,\nAltum: 5,2 dla 120 m",
  },
},
{
  prop: {
    key: "1",
    PRODUCENT: "ATMOS UAV 2",
    NAZWA: "Marlyn (RGB) ",
    ROk_WpROWADZENIA_NA_RYNEk: "2020",
    pLATFORMA: "0",
    wymiary_platformy: "160 x 82 x 70 ",
    wymiary_po_złożeniu: "plecak 80 x 75 x 43 ",
    waga_całkowita: "5.7 ",
    maksymalny_udźwig: "1",
    maksymalna_prędkość: "95",
    maks_dopuszczalna_prędkość_wiatru: "start i lądowanie: 45, lot: 55 ",
    liczba_i_rodzaj_silników: "4 elektryczne ",
    maks_czas_lotu_z_maks_obciążeniem: "55",
    metoda_startu: "VTOL ",
    pOZYCjONOWANIE: "0",
    typ_odbiornika_GNSS: "GPS (L1, L2, L5), GLONASS (L1, L2, L3) ",
    obsługa_korekt: "tak ",
    IMU: "tak ",
    SENSORY: "0",
    cyfrowa_kamera: "Sony UMC-R10C/Sony RX1RII ",
    matryca: "20,1/42,4 ",
    wychylenie_do_zdjęć_ukośnych: "nie ",
    dodatkowe_informacje:
      "możliwość wymiany obiektywów w zależnośći od\ndługości ogniskowej, możliwość zamontowania\nFLIR Duo Pro R",
    img: "https://sklep.navigate.pl/images/produkty//Drony/Drony_Atmos/Marlyn/nowe2/vsig_images/0_atmos-marlyn_674_453_95.jpg",
    przykładowa_rozdzielczość_obrazów:
      "RXIRII: 1,5 cm dla 120 m,\n2 dla 155 m",
  },
},
{
  prop: {
    key: "2",
    PRODUCENT: "Delair",
    NAZWA: "DT18",
    ROk_WpROWADZENIA_NA_RYNEk: "2012",
    pLATFORMA: "0",
    wymiary_platformy: "1200 dł x 1800 rozp",
    wymiary_po_złożeniu: "waliza 1250 x 450 x 300",
    waga_całkowita: "2",
    maksymalny_udźwig: "b.d.",
    maksymalna_prędkość: "61",
    maks_dopuszczalna_prędkość_wiatru: "50",
    liczba_i_rodzaj_silników: "1 elektryczny",
    maks_czas_lotu_z_maks_obciążeniem: "120",
    metoda_startu: "z ręki lub z wyrzutni",
    pOZYCjONOWANIE: "0",
    typ_odbiornika_GNSS: "dwuczęstotliwościowy GNSS (L1, L2)",
    obsługa_korekt: "opcja: PPK",
    IMU: "Applanix o dokładności 0,025˝",
    SENSORY: "0",
    cyfrowa_kamera:
      "zintegorwana kamera przemysłowa Delair (RGB)\nlub multispektralna (Micansense RedEdge)",
    matryca: "21,4 (RGB)",
    wychylenie_do_zdjęć_ukośnych: "nie",
    dodatkowe_informacje:
      "kanały spektralne Micasense RedEdge: niebieski,\nzielony, czerwony, red edge, bliska podczerwień",
    img: "https://www.aiviewgroup.com/assets/img/products/dt18.png",
    przykładowa_rozdzielczość_obrazów:
      "1,1 dla 80 m, 2,1 dla 150 m,\n9,7 dla 700 m",
  },
},
{
  prop: {
    key: "3",
    PRODUCENT: "Delair ",
    NAZWA: "DT26M ",
    ROk_WpROWADZENIA_NA_RYNEk: "2015",
    pLATFORMA: "0",
    wymiary_platformy: "1600 dł x 3300 rozp ",
    wymiary_po_złożeniu: "waliza 1150 x 650 x 680 ",
    waga_całkowita: "15",
    maksymalny_udźwig: "5",
    maksymalna_prędkość: "57",
    maks_dopuszczalna_prędkość_wiatru: "50",
    liczba_i_rodzaj_silników: "1 elektryczny ",
    maks_czas_lotu_z_maks_obciążeniem: "135",
    metoda_startu: "z wyrzutni ",
    pOZYCjONOWANIE: "0",
    typ_odbiornika_GNSS: "dwuczęstotliwościowy GNSS (L1, L2) ",
    obsługa_korekt: "nie ",
    IMU: "nie ",
    SENSORY: "0",
    cyfrowa_kamera:
      "InPixal ASIO 155 Gimbal – sensor EO lub IR do\nwizji dziennej i nocnej",
    matryca: "EO: 720 x 576 px, IR: 640 x 480 px ",
    wychylenie_do_zdjęć_ukośnych: "0-90 ",
    dodatkowe_informacje:
      "EO: zoom opt x36 i FOV 1,7-56°, IR: zoom cyf\ni FOV 17,7°, dł fali 8-14 µm; śledzenie wideo",
    img: "https://delair.aero/wp-content/uploads/2016/10/01-DT26M-up.jpg",
    przykładowa_rozdzielczość_obrazów: "b.d. ",
  },
},]